Capstone/Capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('magnifier.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Capstone/magnifier/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
__author__ = 'Jiexun Li'

from django.urls import path
from . import views

app_name = 'magnifier'

urlpatterns=[
    path('', views.index, name='index'),
    path('result/', views.upload_image, name = 'result'),
]

Capstone/magnifier/models.py


# Create your models here.
from django.db.models import *
from django.utils import timezone
from django.db import models


#class UploadImage(models.Model):
#    upload_image = ImageField(upload_to='upload_image')



Capstone/magnifier/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, render_to_response, redirect
from django.contrib.auth import authenticate, logout, login
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.utils.six import BytesIO
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from .models import *
from django.template import loader
import os
from django.utils import datastructures
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

def index(request):
    context = {
        'title':'well come to magnifier',
    }
    return render(request, 'index.html', context)

def upload_image(request):
    up_img = request.FILES['up_img']

    # write file to the media folder
    file_path = os.path.join('upload_image', up_img.name)
    with open(os.path.join(settings.MEDIA_ROOT, file_path), 'wb') as f:
        for chunk in up_img.chunks():
            f.write(chunk)

    # result image file path
    result_file_path = os.path.join('result_image', up_img.name)
    with open(os.path.join(settings.MEDIA_ROOT, result_file_path), 'wb') as f:
        for chunk in up_img.chunks():
            f.write(chunk)
    # allow the frontend to access the uploaded media
    context = {
        'up_img_url':os.path.join('../media/', file_path),
        'res_img_url':os.path.join('../media/',result_file_path),
    }

    return render(request, 'result.html', context)

Capstone/magnifier/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
<h1>{{ title }}</h1>

<form action="{% url 'magnifier:result'%}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>图片：<input type="file" name="up_img"></h3>
    <button type="submit">提交</button>
</form>
</body>
</html>

Capstone/magnifier/templates/result.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result</title>
</head>
<body>
<li>this is the content: {{ title }}</li>
<li>upload image: <img src={{ up_img_url }}> </li>
<li>result image: <img src={{ res_img_url }}></li>




</body>
</html>